In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('heart_disease_data.csv')
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

CHECKING FOR IMBALANCE DATASET

In [3]:
df.isnull().value_counts() #no empty values present

age    sex    cp     trestbps  chol   fbs    restecg  thalach  exang  oldpeak  slope  ca     thal   target
False  False  False  False     False  False  False    False    False  False    False  False  False  False     303
dtype: int64

In [4]:
df['target'].value_counts() #dataset is balanced

1    165
0    138
Name: target, dtype: int64

SPLITING THE DATA

In [5]:
x=df.drop('target',axis=1)
y=df['target']


MODEL SELECTION

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

USING LIBRARYS

In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import KFold
import numpy as np
from sklearn.model_selection import GridSearchCV

In [8]:
log_class = LogisticRegression()
grid = {'C':10.0**np.arange(-3,3),'penalty':['l1','l2']}
cv = KFold(n_splits=5 , shuffle = False , random_state = None)

In [9]:
clf = GridSearchCV(log_class,grid,cv = cv,n_jobs=-1,scoring='f1_macro')
clf.fit(X_train,y_train)

c:\PYTHON\lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
30 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "c:\PYTHON\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\PYTHON\lib\site-packages\sklearn\linear_model\_logistic.py", line 1162, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "c:\PYTHON\lib\site-packages\sklearn\linear_model\_logistic.py", line 54, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, 

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [21]:
y_pred = clf.predict(X_test)
print("testing/accuracy score:: ",accuracy_score(y_test,y_pred)*100,"%")
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print("training score:: ",clf.score(X_train,y_train),"%")
print("recall:: ",(25/(25+3))*100)
print("precision:: ",(25/(25+4))*100)
print("f1 score",((2*0.86*0.89)/(0.86+0.89))*100)

testing/accuracy score::  88.52459016393442 %
              precision    recall  f1-score   support

           0       0.89      0.86      0.88        29
           1       0.88      0.91      0.89        32

    accuracy                           0.89        61
   macro avg       0.89      0.88      0.88        61
weighted avg       0.89      0.89      0.89        61

[[25  4]
 [ 3 29]]
training score::  0.846153846153846 %
recall::  89.28571428571429
precision::  86.20689655172413
f1 score 87.47428571428571


RANDOM FOREST

In [11]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=100)
classifier.fit(X_train,y_train)
y_pred = classifier.predict(X_test)
print(accuracy_score(y_test,y_pred)*100," %")
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

85.24590163934425  %
              precision    recall  f1-score   support

           0       0.86      0.83      0.84        29
           1       0.85      0.88      0.86        32

    accuracy                           0.85        61
   macro avg       0.85      0.85      0.85        61
weighted avg       0.85      0.85      0.85        61

[[24  5]
 [ 4 28]]


DECISION TREE

In [12]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier()
dtree.fit(X_train,y_train)
y_pred = dtree.predict(X_test)
print(accuracy_score(y_test,y_pred)*100," %")
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

83.60655737704919  %
              precision    recall  f1-score   support

           0       0.79      0.90      0.84        29
           1       0.89      0.78      0.83        32

    accuracy                           0.84        61
   macro avg       0.84      0.84      0.84        61
weighted avg       0.84      0.84      0.84        61

[[26  3]
 [ 7 25]]


LOGISTIC REGRESSION USING SCALED PROCESS 

we are scaling to make all feature values with same scale (mean =0 and var=1) 

In [13]:
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()
X_train_scale = scale.fit_transform(X_train)
X_test_scale = scale.transform(X_test)
model = LogisticRegression()
model.fit(X_train_scale,y_train)
y_pred = model.predict(X_test_scale)
print(accuracy_score(y_test,y_pred)*100," %")
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))


85.24590163934425  %
              precision    recall  f1-score   support

           0       0.83      0.86      0.85        29
           1       0.87      0.84      0.86        32

    accuracy                           0.85        61
   macro avg       0.85      0.85      0.85        61
weighted avg       0.85      0.85      0.85        61

[[25  4]
 [ 5 27]]


SVM

In [14]:
from sklearn.svm import SVC
svc = SVC()
svc.fit(X_train,y_train)
svc_pred = svc.predict(X_test)
print(accuracy_score(y_test,y_pred)*100," %")
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

85.24590163934425  %
              precision    recall  f1-score   support

           0       0.83      0.86      0.85        29
           1       0.87      0.84      0.86        32

    accuracy                           0.85        61
   macro avg       0.85      0.85      0.85        61
weighted avg       0.85      0.85      0.85        61

[[25  4]
 [ 5 27]]


In [15]:
param_grid = {'C': [0.1,1, 10, 100], 'gamma': [1,0.1,0.01,0.001]} 
grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=2)
grid.fit(X_train,y_train)


Fitting 5 folds for each of 16 candidates, totalling 80 fits
[CV] END .....................................C=0.1, gamma=1; total time=   0.0s
[CV] END .....................................C=0.1, gamma=1; total time=   0.0s
[CV] END .....................................C=0.1, gamma=1; total time=   0.0s
[CV] END .....................................C=0.1, gamma=1; total time=   0.0s
[CV] END .....................................C=0.1, gamma=1; total time=   0.0s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.0s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.0s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.0s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.0s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.0s
[CV] END ..................................C=0.1, gamma=0.01; total time=   0.0s
[CV] END ..................................C=0.1

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100],
                         'gamma': [1, 0.1, 0.01, 0.001]},
             verbose=2)

In [16]:
y_pred=grid.predict(X_test)
print(accuracy_score(y_test,y_pred)*100," %")
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

67.21311475409836  %
              precision    recall  f1-score   support

           0       0.67      0.62      0.64        29
           1       0.68      0.72      0.70        32

    accuracy                           0.67        61
   macro avg       0.67      0.67      0.67        61
weighted avg       0.67      0.67      0.67        61

[[18 11]
 [ 9 23]]
